######################################################################
#  Project Makefile
######################################################################

# The target name is the name of the project
TARGET  = $(shell basename $(CURDIR))
# The source files
SRC     = src/main.c

all: elf bin

include ../../../Makefile.mk

